export enum AppErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
  ARTICLE_UNAVAILABLE = 'ARTICLE_UNAVAILABLE',
  PRICE_CHANGED = 'PRICE_CHANGED',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  QUANTITY_EXCEEDS_STOCK = 'QUANTITY_EXCEEDS_STOCK',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  MECHANIC_APPLICATION_ALREADY_EXISTS = 'MECHANIC_APPLICATION_ALREADY_EXISTS',
  COD_THRESHOLD_EXCEEDED = 'COD_THRESHOLD_EXCEEDED',
  BACKOFFICE_UNAVAILABLE = 'BACKOFFICE_UNAVAILABLE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export interface ApiErrorResponse {
  statusCode: number;
  errorCode: AppErrorCode;
}
