
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The runtime client connects through PgBouncer (transaction mode) via the
// pooled DATABASE_URL declared in schema.prisma. Migrations and other CLI
// commands need session-level features that PgBouncer's transaction mode
// breaks, so they must use a direct connection. Prefer DIRECT_URL when set and
// fall back to DATABASE_URL for environments without a pooler (local, CI).
const migrationDatabaseUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!migrationDatabaseUrl) {
  throw new Error(
    "Set DIRECT_URL (direct, non-pooled connection) or DATABASE_URL for Prisma CLI commands.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: migrationDatabaseUrl,
  },
});
